name: Build and test
description: Build and test

runs:
  using: composite
  steps:
    - name: Build Redis
      working-directory: redis
      shell: bash
      run: |
        make install
        echo "REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server" >> $GITHUB_ENV
        echo "$GITHUB_WORKSPACE/redis/src" >> $GITHUB_PATH
        export PATH="$GITHUB_WORKSPACE/redis/src:$PATH"
        redis-server --version
    - name: Build modules
      shell: bash
      run: |
        echo ${PATH}
        make --version
        make build
    - name: Run tests
      shell: bash
      run: |
        . venv/bin/activate
        make test
