
/*
* Copyright 2018-2019 Redis Labs Ltd. and Contributors
*
* This file is available under the Redis Labs Source Available License Agreement
*/

#ifndef REDISTIMESERIES_MODULE_VERSION

#define REDISTIMESERIES_VERSION_MAJOR 1

#ifndef REDISTIMESERIES_MASTER_BUILD
#define REDISTIMESERIES_MASTER_BUILD 0
#endif

#if REDISTIMESERIES_MASTER_BUILD > 0
#define REDISTIMESERIES_VERSION_MINOR 999
#else
#define REDISTIMESERIES_VERSION_MINOR 0
#endif

#ifndef REDISTIMESERIES_VERSION_PATCH
#define REDISTIMESERIES_VERSION_PATCH 0
#endif

#define REDISTIMESERIES_SEMANTIC_VERSION(major, minor, patch) \
  (major * 10000 + minor * 100 + patch)

#define REDISTIMESERIES_MODULE_VERSION REDISTIMESERIES_SEMANTIC_VERSION(REDISTIMESERIES_VERSION_MAJOR, REDISTIMESERIES_VERSION_MINOR, REDISTIMESERIES_VERSION_PATCH)

#endif
