name: Run module tests

inputs:
  run_valgrind:
    description: 'Run valgrind on the tests'
    type: string
    default: 0
  run_sanitizer:
    description: 'Run sanitizer on the tests'
    type: string
    default: ''
  quick:
    description: 'Run with quick flag'
    type: string
    default: ''
  use-venv:
    type: string
    description: "Specify whether to use the environment or not"
    default: '0'


runs:
  using: composite
  steps:
    - name: Run tests
      shell: bash
      run: |
        if command -v scl_source &> /dev/null
        then
            . scl_source enable devtoolset-11 || true
        fi
        if [[ "${{ inputs.use-venv }}" == "1" ]]; then
          . venv/bin/activate
        fi
        for i in $(seq 1 100); do echo "=== Run $i/100 ==="; make test TEST=test_asm:test_asm_with_data_and_queries_during_migrations VG=${{inputs.run_valgrind}} SAN=${{inputs.run_sanitizer}} QUICK=${{inputs.quick}} REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server 2>&1 | tee -a /tmp/test_output.log; if [ ${PIPESTATUS[0]} -ne 0 ]; then echo "=== FAILED on run $i ==="; exit 1; fi; done
