name: Run module tests

inputs:
  run_valgrind:
    description: 'Run valgrind on the tests'
    type: string
    default: 0
  run_sanitizer:
    description: 'Run sanitizer on the tests'
    type: string
    default: ''
  quick:
    description: 'Run with quick flag'
    type: string
    default: ''
  use-venv:
    type: string
    description: "Specify whether to use the environment or not"
    default: '0'


runs:
  using: composite
  steps:
    - name: Run tests
      shell: bash
      env:
        INPUT_RUN_VALGRIND: ${{ inputs.run_valgrind }}
        INPUT_RUN_SANITIZER: ${{ inputs.run_sanitizer }}
        INPUT_QUICK: ${{ inputs.quick }}
        INPUT_USE_VENV: ${{ inputs.use-venv }}
      run: |
        if command -v scl_source &> /dev/null
        then
            . scl_source enable devtoolset-11 || true
        fi
        if [[ "$INPUT_USE_VENV" == "1" ]]; then
          . venv/bin/activate
        fi
        # Capture test output to file for parsing by capture-test-results action
        TEST_OUTPUT_FILE="$GITHUB_WORKSPACE/test_output.log"
        make test VG="$INPUT_RUN_VALGRIND" SAN="$INPUT_RUN_SANITIZER" QUICK="$INPUT_QUICK" \
          REDIS_SERVER="$GITHUB_WORKSPACE/redis/src/redis-server" 2>&1 | tee "$TEST_OUTPUT_FILE"
        echo "TEST_OUTPUT_FILE=$TEST_OUTPUT_FILE" >> $GITHUB_ENV
        exit ${PIPESTATUS[0]}
