name: Event Weekly

on:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  id-token: write
  contents: read

jobs:
  run-benchmarks:
    uses: ./.github/workflows/benchmark-runner.yml
    secrets: inherit
    with:
      extended: true

  jobs:
  build-linux-x86:
    uses: ./.github/workflows/flow-linux-x86.yml
    with:
      os: bionic focal jammy rocky8 rocky9 bullseye amazonlinux2 mariner2
      redis-ref: ${{inputs.redis-ref || 'unstable'}}
    secrets: inherit
  ubuntu-arm64:
    uses: ./.github/workflows/flow-ubuntu-arm.yml
    with:
      redis-ref: ${{inputs.redis-ref || 'unstable'}}
    secrets: inherit
  macos:
    uses: ./.github/workflows/flow-macos.yml
    with:
      redis-ref: ${{inputs.redis-ref || 'unstable'}}
    secrets: inherit
  alpine:
    uses: ./.github/workflows/flow-alpine.yml
    with:
      redis-ref: ${{inputs.redis-ref || 'unstable'}}
    secrets: inherit
  linux-valgrind:
    uses: ./.github/workflows/flow-linux-x86.yml
    with:
      os: jammy
      redis-ref: unstable
      run_valgrind: true
    secrets: inherit
  linux-sanitizer:
    uses: ./.github/workflows/flow-linux-x86.yml
    with:
      os: jammy
      redis-ref: unstable
      run_sanitizer: true
    secrets: inherit
