name: build for Jammy-x86

on:
#  pull_request:
  push:
#    branches:
#      - master
#      - 1.10
#      - /^feature-.*$/
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-jammy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l -o pipefail {0}
    container:
      image: ubuntu:jammy
    steps:
      - name: Install pre-checkout dependencies
        run: apt-get update && apt-get install -y git
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install dependencies
        working-directory: .install
        shell: bash
        run: |
          ./ubuntu_22.04.sh
      - name: Get Redis
        uses: actions/checkout@v4
        with:
          repository: redis/redis
          ref: '7.2.1'  # todo: use this is a parameter when we have flows for multiple platforms
          path: redis
      - name: Build Redis
        working-directory: redis
        run: make install
      - name: Make setup
        shell: bash
        run: |
          make setup
      - name: Build and test TS
        shell: bash
        run: |
          make test
      - name: Pack module
        shell: bash
        run: make pack BRANCH=${{ github.head_ref }} SHOW=1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
      - name: Upload artifacts to s3 - staging
        if: ${{ startsWith(github.head_ref, 'feature-') }}
        shell: bash
        run: |
          make upload-artifacts SHOW=1 VERBOSE=1
          make upload-release SHOW=1 STAGING=1 VERBOSE=1
      - name: Upload artifacts to s3 - release  # todo: trigger this manually instead
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        shell: bash
        run: make upload-release SHOW=1 VERBOSE=1
