name: build for Jammy-x86

on:
#  pull_request:
  push:
#    branches:
#      - master
#      - 1.10
#      - /^feature-.*$/
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  recent-ubuntu:
    runs-on: ${{ matrix.builder.os }}
    env:
      TAGGED: ${{ needs.setup-environment.outputs.TAGGED }}
      VERSION: ${{ needs.setup-environment.outputs.TAG }}
      BRANCH: ${{ needs.setup-environment.outputs.BRANCH }}
      TAG_OR_BRANCH: ${{ needs.setup-environment.outputs.TAG_OR_BRANCH}}
    strategy:
      fail-fast: false
      matrix:
        redis-version: [ "unstable" ]
        builder: [
          { os: 'ubuntu-22.04', nick: 'jammy' },
        ]
    defaults:
      run:
        shell: bash -l -eo pipefail {0}
    steps:
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential autoconf automake libtool cmake lcov valgrind
      - name: Setup Python for testing
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          architecture: 'x64'
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Python dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install -r tests/flow/requirements.txt
          python3 -m pip install jinja2 ramp-packer
          ./sbin/setup
      - name: Checkout Redis
        uses: actions/checkout@v3
        with:
          repository: 'redis/redis'
          ref: ${{ matrix.redis-version }}
          path: 'redis'
      - name: Build Redis
        run: |
          cd redis && make -j `nproc`
          echo "REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/redis/src" >> $GITHUB_PATH
          export PATH="$GITHUB_WORKSPACE/redis/src:$PATH"
          redis-server --version
      - name: Build
        run: |
          source .venv/bin/activate
          git submodule update --init --recursive
          make -j 4
      - name: Run tests
        run: |
          source .venv/bin/activate
          make test REDIS_SERVER=$GITHUB_WORKSPACE/redis/src/redis-server
      - name: Pack module
        shell: bash
        run: make pack BRANCH=${{ github.head_ref }} SHOW=1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
      - name: Upload artifacts to s3 - staging
        if: ${{ startsWith(github.head_ref, 'feature-') }}
        shell: bash
        run: |
          make upload-artifacts SHOW=1 VERBOSE=1
          make upload-release SHOW=1 STAGING=1 VERBOSE=1
      - name: Upload artifacts to s3 - release  # todo: trigger this manually instead
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        shell: bash
        run: make upload-release SHOW=1 VERBOSE=1
